server:
  port: 6600 #HTTP (Tomcat) port
  servlet:
    context-path: /api

spring:
  application:
    name: alexa-reviews
  datasource:
   url: jdbc:h2:file:/home/siri/Downloads/alexa/alexadb
   driverClassName: org.h2.Driver
   username: sa
   password:
  jpa:
   hibernate:
    ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false

